# Streamlit secrets configuration
# Add your Gemini API key here (this file should NOT be committed to git)

GEMINI_API_KEY = "AIzaSyARKyeo0-0Zu8lHRrq-peDV3UsoEEfmeSQ"

# Alternative: Set as environment variable
# export GEMINI_API_KEY="your-api-key"
# or in Windows: set GEMINI_API_KEY=your-api-key